
// This code was automatically generated by treebuilder

#ifndef PROLOG_SELECTOR_
#define PROLOG_SELECTOR_   1

#include <iostream>

namespace prolog { 

   enum selector
   {      
      sel_atom, sel_var, sel_bigint, sel_double, 
      sel_functional, sel_int, sel_string
   };

   const char* getcstring( selector );

   inline std::ostream& operator << ( std::ostream& out, selector sel )
      { out << getcstring( sel ); return out; }

}

#endif

