#ifndef AST_GENERIC_H
#define AST_GENERIC_H

#include "array_access.h"
#include "base.h"
#include "binary.h"
#include "block.h"
#include "break.h"
#include "case_arm.h"
#include "cast.h"
#include "continue.h"
#include "cycles.h"
#include "decl.h"
#include "expr.h"
#include "funccall.h"
#include "funcdef.h"
#include "go_to.h"
#include "identifier.h"
#include "if.h"
#include "init_list.h"
#include "label.h"
#include "literal.h"
#include "member_access.h"
#include "none.h"
#include "program.h"
#include "ptr_member.h"
#include "return.h"
#include "stmt.h"
#include "switch.h"
#include "ternary.h"
#include "unary.h"

#endif
