
// Parser generated by Maphoon 2021.
// Written by Hans de Nivelle, March 2021.
// See the licence that was included with the code.

#include "parser.h"

#line 141 "idee.x"


size_t 
parser::statesymbol::hash::operator( ) ( const statesymbol& ss ) const
{
   return ss.state + ( ss.type << 4 ) + ( ss.type );
}

bool
parser::statesymbol::equal_to::operator( ) ( const statesymbol& ss1,
                                                            const statesymbol& ss2 ) const
{
   return ss1. state == ss2. state && ss1. type == ss2. type;
}


// Definitions of the reduction functions:

void parser::body0( )
{
#line 53 "grammar.m"

   std::cout << "RESULT:\n" << (topsymbol(2).get<tree>()) << '\n';
   if( (topsymbol(2).get<tree>()). nrsubtrees( ) == 0 && (topsymbol(2).get<tree>()). hasstring( ) && (topsymbol(2).get<tree>()). getstring( ) == "quit" )
   {
      std::cout << "quitting\n"; 
      timetosaygoodbye = true; 
   }
   // print a prompt: 
   std::cout << ":- "; 
}

tree parser::body2( )
{
#line 68 "grammar.m"

  return (topsymbol(1).get<tree>());
}

tree parser::body3( )
{
#line 72 "grammar.m"

  return tree( std::string( "+" ), { (topsymbol(3).get<tree>()), (topsymbol(1).get<tree>()) } );
}

tree parser::body4( )
{
#line 76 "grammar.m"

  return tree( std::string( "-" ), { (topsymbol(3).get<tree>()), (topsymbol(1).get<tree>()) } );
}

tree parser::body5( )
{
#line 82 "grammar.m"

   return (topsymbol(1).get<tree>());
}

tree parser::body6( )
{
#line 86 "grammar.m"

   return tree( std::string( "*" ), { (topsymbol(3).get<tree>()), (topsymbol(1).get<tree>()) } );
}

tree parser::body7( )
{
#line 90 "grammar.m"

   return tree( std::string( "/" ), { (topsymbol(3).get<tree>()), (topsymbol(1).get<tree>()) } );
}

tree parser::body8( )
{
#line 96 "grammar.m"

  return (topsymbol(1).get<tree>());
}

tree parser::body9( )
{
#line 100 "grammar.m"

  return tree( std::string( "-" ), { (topsymbol(1).get<tree>()) } );
}

tree parser::body10( )
{
#line 106 "grammar.m"

  return tree( (topsymbol(1).get<bigint>()) );
}

tree parser::body11( )
{
#line 110 "grammar.m"

  return tree( (topsymbol(1).get<double>()) );
}

tree parser::body12( )
{
#line 114 "grammar.m"

  return tree( (topsymbol(1).get<std::string>()) );
}

tree parser::body13( )
{
#line 118 "grammar.m"

  return tree( (topsymbol(4).get<std::string>()), (topsymbol(2).get<util::shared_vector<tree>>()) );
}

tree parser::body14( )
{
#line 122 "grammar.m"

  return (topsymbol(2).get<tree>());
}

util::shared_vector<tree> parser::body15( )
{
#line 128 "grammar.m"

  util::shared_vector< tree > vec;
  vec. push_back( (topsymbol(1).get<tree>()) );
  return vec;
}

util::shared_vector<tree> parser::body16( )
{
#line 134 "grammar.m"

  (topsymbol(3).get<util::shared_vector<tree>>()). push_back( (topsymbol(1).get<tree>()) );
  return (topsymbol(3).get<util::shared_vector<tree>>());
}



#line 1 "reduce"

void parser::reduce( symboltype lefttype,
               symbol::attrtype&& attr, size_t rightsize )
{
   if( debug >= 2 )
   {
      std::cout << "popping " << rightsize << " state/symbol from stack "; 
      std::cout << "and reducing into " << lefttype << "\n";
   }

#if false
   // This works only if symbol has an info type: 

   std::optional< symbol::infotype > info;
      // Look for the first symbol that has info:

   for( auto p = symbolstack. end( ) - rightsize; 
        p != symbolstack. end( ); ++ p ) 
   {
      // If we encounter first defined, we move into info. 
      // For later defineds, we call merge_infos( ).

      if( p -> info. has_value( )) 
      {
         if( info. has_value( ))
            merge_infos( info.value( ), std::move( p -> info.value() ));
         else
            info = std::move( p -> info );
      }
   }
#endif 

   while( rightsize )
   {
      statestack. pop_back( );
      symbolstack. pop_back( );
      -- rightsize; 
   }
  
   // It remains to do the goto: 

   statestack. push_back( shifts. at( { statestack. back( ), lefttype } ));

#if false
   symbolstack. emplace_back( lefttype, info, std::move( attr ));
#else
   symbolstack. emplace_back( lefttype, std::move( attr ));
#endif 
}

#line 1 "parse"

symbol 
parser::parse( symboltype startsym )
{
   if( debug >= 2 ) 
   {
      std::cout << "Starting parser:\n";

      if( ! std::is_nothrow_move_constructible<symbol> :: value )
      {
         std::cout << "class symbol is not nothrow move constructible\n";
         std::cout << "   (this causes loss of efficiency)\n"; 
      }
      else
      {
         std::cout << "class symbol is nothrow move constructible\n";
         std::cout << "   (that is good)\n";
      }
   }

   if( debug >= 1 && 
          startsymbols. find( startsym ) == startsymbols. end( ))
   {
      std::cout << "startsymbol " << startsym << " is not a start symbol\n";
   }
 
   const auto& startinfo = startsymbols. at( startsym );
   statestack. push_back( startinfo. first );
  
mainloop: 
   if( debug >= 1 ) 
      print( std::cout ); 

   if( timetosaygoodbye )
   {
      if( debug >= 2 ) 
         std::cout << "time to say goodbye\n";

      symbol res = std::move( symbolstack. back( ));
      symbolstack. pop_back( );
      statestack. pop_back( );
      return res; 
   }
 
   size_t shift = reductioninfo. size( );  // Means undefined. 
   std::vector< size_t > redcandidates;

   // Decide if our state is a simple state:

   const auto& redinfo = reductioninfo[ statestack. back( ) ]; 

   // If the state is non-trivial, we need a lookahead:

   if( redinfo. first != 'T' && !lookahead. has_value( )) 
      lookahead =  readsymbol( r ); 
  

   if( debug >= 3 && lookahead. has_value( ))
      std::cout << "lookahead " << lookahead. value( ) << "\n";

   switch( redinfo. first ) 
   {
   case 'N': 
   {
      auto p = shifts. find( 
               statesymbol( statestack.back( ), lookahead. value( ). type ));
      if( p != shifts. end( ))
         shift = p -> second;
      break;
   }
   case 'D':
   {
      auto p = shifts. find(
               statesymbol( statestack.back( ), lookahead. value( ). type ));
      if( p != shifts. end( ))
         shift = p -> second;
      else
         redcandidates. push_back( redinfo. second ); 
      break;
   }
   case 'H':
   {
      auto p = shifts. find(
               statesymbol( statestack. back( ), lookahead. value( ). type ));
      if( p != shifts. end( ))
         shift = p -> second; 
     
      auto q = reductions. find( 
               statesymbol( statestack. back( ), lookahead. value( ). type ));
      if( q != reductions. end( ))
         redcandidates = q -> second; 
      break;
   }
   case 'T':
      redcandidates. push_back( redinfo. second );
      break;   
   default:
      std::cout << redinfo.first << "\n";
      throw std::logic_error( "reduction info not recognized" );
   }
  
   if( debug >= 3 )
   { 
      if( shift != reductioninfo. size( ))
         std::cout << "shift candidate " << shift << "\n";

      if( redcandidates. size( )) 
      {
         std::cout << "reduction candidates: "; 
         for( size_t i = 0; i != redcandidates. size( ); ++ i )
            std::cout << redcandidates[i] << " ";
         std::cout << "\n";
      }
      else
         std::cout << "there are no reduction candidates\n";
   }

   // We need to find a reduction that agrees to be reduced: 

   for( const auto& r : redcandidates ) 
   {
      if( debug >= 3 ) 
         std::cout << "trying to reduce rule " << r << "\n";

      switch(r)
      {
      case 0:
         body0( );
         reduce( sym_mainloop, std::monostate( ), 3 );
         goto mainloop;
         break;
      case 1:
         reduce( sym_mainloop, std::monostate( ), 0 );
         goto mainloop;
         break;
      case 2:
         reduce( sym_expr, body2( ), 1 );
         goto mainloop;
         break;
      case 3:
         reduce( sym_expr, body3( ), 3 );
         goto mainloop;
         break;
      case 4:
         reduce( sym_expr, body4( ), 3 );
         goto mainloop;
         break;
      case 5:
         reduce( sym_expr1, body5( ), 1 );
         goto mainloop;
         break;
      case 6:
         reduce( sym_expr1, body6( ), 3 );
         goto mainloop;
         break;
      case 7:
         reduce( sym_expr1, body7( ), 3 );
         goto mainloop;
         break;
      case 8:
         reduce( sym_expr2, body8( ), 1 );
         goto mainloop;
         break;
      case 9:
         reduce( sym_expr2, body9( ), 2 );
         goto mainloop;
         break;
      case 10:
         reduce( sym_expr3, body10( ), 1 );
         goto mainloop;
         break;
      case 11:
         reduce( sym_expr3, body11( ), 1 );
         goto mainloop;
         break;
      case 12:
         reduce( sym_expr3, body12( ), 1 );
         goto mainloop;
         break;
      case 13:
         reduce( sym_expr3, body13( ), 4 );
         goto mainloop;
         break;
      case 14:
         reduce( sym_expr3, body14( ), 3 );
         goto mainloop;
         break;
      case 15:
         reduce( sym_exprlist, body15( ), 1 );
         goto mainloop;
         break;
      case 16:
         reduce( sym_exprlist, body16( ), 3 );
         goto mainloop;
         break;
 
      default:
         throw std::logic_error( "reducing unknown rule" );  
      }
   }

   if( shift < reductioninfo. size( ))
   {
      if( debug >= 2 ) 
         std::cout << "shifting S" << shift << "\n";

      statestack. push_back( shift );
      symbolstack. push_back( std::move( lookahead. value( ) ));
      lookahead. reset( );

      if( lasterror < 10000 )
         ++ lasterror; 

      goto mainloop;
   }

   if( symbolstack. size( ) == 1 && symbolstack. front( ). type == startsym )
   {
      if( debug >= 2 ) 
         std::cout << "we accept the input\n";

      symbol res = std::move( symbolstack. front( ));
      symbolstack. clear( );
      statestack. pop_back( );
      return res;
   }

#line 1 "startpoint"

   unsigned int patience = syntaxerror( ); 
   if( patience ) 
   {
      if( debug >= 2 )
         std::cout << "trying to recover\n";

      if( debug >= 2 )
         std::cout << "patience remaining = " << patience << "\n";

      std::vector< std::pair< size_t, size_t >> shiftrecover; 
         // We collect the levels whose state can shift the  _recover_ 
         // symbol, 
         // combined with the states that will be reached after the shifts.

      for( size_t level = 0; level != statestack. size( ); ++ level )
      {
         size_t s = statestack[ level ];

         if( reductioninfo[s]. first == 'N' ||
             reductioninfo[s]. first == 'D' ||
             reductioninfo[s]. first == 'H' )
         {
            auto p = shifts. find( statesymbol( s, sym__recover_ ));
            if( p != shifts. end( ))
               shiftrecover. push_back( std::pair( level, p -> second ));
         }
      } 

      std::cout << "{";
      for( auto p = shiftrecover. begin( ); p != shiftrecover. end( ); ++ p )
      {
         if( p != shiftrecover. begin( ))
            std::cout << ", ";
         else
            std::cout << " ";
         std::cout << ( p -> first ) << "/" << ( p -> second );
      }
      std::cout << " }\n";

      if( shiftrecover. size( ) == 0 )
      {
         std::cout << "no recovering shifts found\n";
         std::cout << lookahead. value( ) << "\n";
         return lookahead. value( );
      }

      std::cout << "lookahead = " << lookahead. value( ) << "\n";

      // While we still have patience, and the lookahead is not
      // in the terminator set, we try to recover: 
 
      while( patience && 
             startinfo. second. count( lookahead. value( ). type ) == 0 )
      {
         // We look in shiftrecover for the highest level on
         // which we could shift current lookahead after shifting the 
         // _recover_ symbol. 

         size_t rec = shiftrecover. size( ); 
         while( rec != 0 ) 
         { 
            -- rec; 
            size_t s = shiftrecover[ rec ]. second; 
            
            if( reductioninfo[s]. first == 'N' ||
                reductioninfo[s]. first == 'D' ||
                reductioninfo[s]. first == 'H' )
            {
               auto after = shifts. find( 
                      statesymbol( s, lookahead. value( ). type ));

               if( after != shifts. end( ))
               {
                  std::cout << rec << " is candidate\n";
                  std::cout << "recovery will be into state ";
                  std::cout << after -> second << "\n";

                  while( statestack. size() > shiftrecover[ rec ]. first + 1 )
                  {
                     statestack. pop_back( );
                     symbolstack. pop_back( );  
                  } 
                  
                  statestack. push_back(s);
#if false
                  symbolstack. push_back( 
                     symbol( sym__recover_, 
                             std::optional< symbol::infotype > ( ))); 
#else
                  symbolstack. push_back( 
                     symbol( sym__recover_ ));
#endif 
                  statestack. push_back( after -> second );
                  symbolstack. push_back( std::move( lookahead. value( ) ));
                  lookahead. reset( );

                  lasterror = 0;

                  print( std::cout );  
                  std::cout <<  "we are recovered!" << "\n\n";
                  goto mainloop; 
               } 
            }
         }

         // We throw away the current lookahead,
         // and lose a bit of our patience. 

         std::cout << "not yet recovered, patience = " << patience << "\n";
         lookahead =  readsymbol( r ); 

         -- patience; 
      }
   }

   // That's it. Game over. We lost.

   if( debug )
   {
      if( !patience ) 
         std::cout << "recovery ran out of patience\n";
      else
         std::cout << "reached a terminator\n";
   }

#if false
   return symbol( sym__recover_,
                  std::optional< symbol::infotype > ( ) );
#else
   return symbol( sym__recover_ );
#endif

}

#if ! false 

unsigned int 
parser::syntaxerror( )
{
   if( lasterror > 3 ) 
   {
      std::cout << "this looks like a new syntax error\n"; 
      return 6;
   }
   else
   {
      std::cout << "this looks like a failed recovery\n";
      return 6 - lasterror;
         // Possible because lasterror <= 3.
   }   
}

#endif

void 
parser::print( std::ostream& out ) const
{
   out << "Statestack: ";
   for( auto s : statestack )
      out << "S" << s << " ";
   out << "\n";

   out << "Symbolstack: ";
   for( const auto& s : symbolstack )
      out << s << "  ";
   out << "\n";
   if( lasterror < 10000 )
      out << "last error was " << lasterror << " symbols ago\n";

}

std::unordered_map< symboltype, std::pair< size_t, std::unordered_set< symboltype >>> parser::startsymbols =
{
   { sym_mainloop, { 0, { sym_EOF }} }
};

std::vector< std::pair< char, size_t >> parser::reductioninfo =
{
   { 'D', 1 }, { 'N', 0 }, { 'T', 8 }, { 'N', 0 }, { 'T', 5 }, { 'N', 0 }, { 'D', 2 }, { 'D', 12 },
   { 'N', 0 }, { 'T', 10 }, { 'T', 11 }, { 'T', 9 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 }, { 'N', 0 },
   { 'N', 0 }, { 'N', 0 }, { 'T', 0 }, { 'T', 14 }, { 'T', 6 }, { 'T', 7 }, { 'D', 3 }, { 'D', 4 },
   { 'T', 15 }, { 'N', 0 }, { 'N', 0 }, { 'T', 13 }, { 'T', 16 }
};

parser::statesymbol::map< size_t > parser::shifts =
{
   { { 26, sym_MINUS }, 3 }, { { 26, sym_LPAR }, 5 }, { { 26, sym_expr }, 28 }, { { 26, sym_INTEGER }, 9 }, { { 26, sym_DOUBLE }, 10 },
   { { 26, sym_expr2 }, 4 }, { { 25, sym_COMMA }, 26 }, { { 26, sym_expr1 }, 6 }, { { 25, sym_RPAR }, 27 }, { { 23, sym_DIVIDES }, 14 },
   { { 23, sym_TIMES }, 13 }, { { 22, sym_DIVIDES }, 14 }, { { 22, sym_TIMES }, 13 }, { { 17, sym_expr2 }, 4 }, { { 17, sym_exprlist }, 25 },
   { { 17, sym_DOUBLE }, 10 }, { { 17, sym_INTEGER }, 9 }, { { 17, sym_expr3 }, 2 }, { { 16, sym_INTEGER }, 9 }, { { 16, sym_DOUBLE }, 10 },
   { { 16, sym_expr3 }, 2 }, { { 5, sym_expr3 }, 2 }, { { 5, sym_MINUS }, 3 }, { { 5, sym_expr2 }, 4 }, { { 16, sym_STRING }, 7 },
   { { 5, sym_expr }, 12 }, { { 5, sym_expr1 }, 6 }, { { 16, sym_expr2 }, 4 }, { { 5, sym_DOUBLE }, 10 }, { { 1, sym_expr2 }, 4 },
   { { 17, sym_expr1 }, 6 }, { { 14, sym_DOUBLE }, 10 }, { { 6, sym_DIVIDES }, 14 }, { { 3, sym_DOUBLE }, 10 }, { { 17, sym_STRING }, 7 },
   { { 3, sym_INTEGER }, 9 }, { { 5, sym_LPAR }, 5 }, { { 1, sym_MINUS }, 3 }, { { 1, sym_STRING }, 7 }, { { 15, sym_DOUBLE }, 10 },
   { { 1, sym_expr }, 8 }, { { 5, sym_STRING }, 7 }, { { 3, sym_expr2 }, 11 }, { { 14, sym_expr3 }, 2 }, { { 3, sym_MINUS }, 3 },
   { { 1, sym_expr1 }, 6 }, { { 7, sym_LPAR }, 17 }, { { 5, sym_INTEGER }, 9 }, { { 3, sym_expr3 }, 2 }, { { 26, sym_expr3 }, 2 },
   { { 3, sym_STRING }, 7 }, { { 1, sym_DOUBLE }, 10 }, { { 6, sym_MINUS }, 16 }, { { 1, sym_expr3 }, 2 }, { { 16, sym_MINUS }, 3 },
   { { 6, sym_TIMES }, 13 }, { { 8, sym_DOT }, 18 }, { { 15, sym_expr3 }, 2 }, { { 13, sym_expr2 }, 20 }, { { 13, sym_MINUS }, 3 },
   { { 13, sym_expr3 }, 2 }, { { 13, sym_LPAR }, 5 }, { { 1, sym_LPAR }, 5 }, { { 13, sym_STRING }, 7 }, { { 26, sym_STRING }, 7 },
   { { 14, sym_LPAR }, 5 }, { { 16, sym_expr1 }, 23 }, { { 13, sym_DOUBLE }, 10 }, { { 14, sym_expr2 }, 21 }, { { 14, sym_MINUS }, 3 },
   { { 14, sym_STRING }, 7 }, { { 13, sym_INTEGER }, 9 }, { { 15, sym_LPAR }, 5 }, { { 17, sym_MINUS }, 3 }, { { 15, sym_expr1 }, 22 },
   { { 15, sym_expr2 }, 4 }, { { 12, sym_RPAR }, 19 }, { { 15, sym_MINUS }, 3 }, { { 3, sym_LPAR }, 5 }, { { 1, sym_INTEGER }, 9 },
   { { 6, sym_PLUS }, 15 }, { { 15, sym_STRING }, 7 }, { { 17, sym_expr }, 24 }, { { 0, sym_mainloop }, 1 }, { { 14, sym_INTEGER }, 9 },
   { { 16, sym_LPAR }, 5 }, { { 17, sym_LPAR }, 5 }, { { 15, sym_INTEGER }, 9 }
};

parser::statesymbol::map< std::vector< size_t >> parser::reductions =
{
   
};



